# Generated by Django 5.0.2 on 2025-12-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=3)),
                ('dias', models.JSONField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=15)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_escolar_desit_api.maestros')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nrc'],
            },
        ),
    ]
